### ISSUE TITLE
cs file naming

### ISSUE THREAD

**Issue by jjsolly** [daveReeves/SpatialSlur#1]
Hi Dave,

Quick one but I just downloaded the binaries and tried to build. There's a bit of a strange issue where the project file is looking for different file names than are existing in the folder structure? 
![snapshot](https://user-images.githubusercontent.com/13330147/36557269-14e2ebfe-1808-11e8-8b7c-77ed42734715.png)

**Comment by davreev** [comment]
Hey James,
I'm midway through pushing a bunch of changes so it's likely that the VS solution file will be confused until I'm finished. Should be good to go by this evening.

**Comment by davreev** [comment]
Ok just made the last push. Let me know if that works out. I'll aim to do big pushes on a separate branch in the future to avoid this sort of thing.
